[package]
name = "aria-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
aria-ebpf-abi = { path = "../abi", features = ["aya-pod"] }
aya.workspace = true
serde.workspace = true
serde_json.workspace = true
libc.workspace = true
fslock.workspace = true
tokio.workspace = true
tracing.workspace = true
