ebpf_path = "/usr/local/lib/libebpf_firewall.so"
trace_backend = "auto"
trace_auto_allow_ringbuf = false

mode = "neutron_managed"
auto_attach = false

pin_path = "/sys/fs/bpf/aria"
state_path = "/var/lib/aria-agent"
iface_pattern = "^tap"
max_port_policies = 16384

listen_addr = "127.0.0.1:8080"
neutron_socket_path = "/run/aria/aria-agent.sock"

log_format = "text"
log_filter = "info"
log_file_path = "/var/log/aria-agent/aria-agent.log"
