[agent]
# If empty, neutron-aria-agent uses socket.gethostname().
host =
managed_domains = acl
resync_interval = 60

[ovs]
bridge = br-int

[aria]
socket_path = /run/aria/aria-agent.sock
request_timeout = 3.0
